import { prisma } from "@/lib/db";

export interface SessionScheduleConfig {
  weekday: number;
  hour: number;
  minute: number;
  durationMins: number;
  sessionPrice: number;
}

export function getSessionScheduleConfig(): SessionScheduleConfig {
  return {
    weekday: Number(process.env.PORTAL_DEFAULT_SESSION_WEEKDAY ?? 2),
    hour: Number(process.env.PORTAL_DEFAULT_SESSION_HOUR ?? 10),
    minute: Number(process.env.PORTAL_DEFAULT_SESSION_MINUTE ?? 0),
    durationMins: Number(process.env.PORTAL_DEFAULT_SESSION_DURATION ?? 60),
    sessionPrice: Number(process.env.PORTAL_SESSION_PRICE ?? 150),
  };
}

/** First session: at least 7 days after assessment, on the configured weekday/time. */
export function getFirstWeeklySlot(after: Date, config: SessionScheduleConfig): Date {
  const start = new Date(after);
  start.setDate(start.getDate() + 7);
  start.setHours(config.hour, config.minute, 0, 0);

  while (start.getDay() !== config.weekday) {
    start.setDate(start.getDate() + 1);
  }

  return start;
}

export function addWeeks(date: Date, weeks: number): Date {
  const next = new Date(date);
  next.setDate(next.getDate() + weeks * 7);
  return next;
}

export async function createPackageSessionsForAssessment(
  patientId: string,
  assessmentId: string,
  packageNumber: number,
  sessionCount: number,
  completedAt: Date,
) {
  const existing = await prisma.session.count({
    where: { assessmentId, status: { not: "cancelled" } },
  });
  if (existing > 0) {
    return { created: 0, skipped: true };
  }

  const config = getSessionScheduleConfig();
  let slot = getFirstWeeklySlot(completedAt, config);
  const sessions = [];

  for (let i = 1; i <= sessionCount; i++) {
    sessions.push({
      patientId,
      assessmentId,
      sessionIndex: i,
      scheduledAt: new Date(slot),
      durationMins: config.durationMins,
      notes: `Package ${packageNumber} — Session ${i} of ${sessionCount}`,
      status: "scheduled",
    });
    slot = addWeeks(slot, 1);
  }

  await prisma.session.createMany({ data: sessions });
  return { created: sessionCount, skipped: false };
}

export async function resetSessionAutomationOnReschedule(sessionId: string) {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    include: { invoice: true },
  });
  if (!session) return;

  if (
    session.invoice?.autoGenerated &&
    session.invoice.status === "pending"
  ) {
    await prisma.invoice.delete({ where: { id: session.invoice.id } });
  }

  await prisma.session.update({
    where: { id: sessionId },
    data: {
      patientReminderSentAt: null,
      doctorReminderSentAt: null,
    },
  });
}
