import { prisma } from "@/lib/db";
import {
  addEasternDays,
  easternToUtc,
  getEasternParts,
} from "@/lib/timezone";

export interface SessionScheduleConfig {
  weekday: number;
  hour: number;
  minute: number;
  durationMins: number;
  sessionPrice: number;
}

export function getSessionScheduleConfig(): SessionScheduleConfig {
  return {
    weekday: Number(process.env.PORTAL_DEFAULT_SESSION_WEEKDAY ?? 2),
    hour: Number(process.env.PORTAL_DEFAULT_SESSION_HOUR ?? 10),
    minute: Number(process.env.PORTAL_DEFAULT_SESSION_MINUTE ?? 0),
    durationMins: Number(process.env.PORTAL_DEFAULT_SESSION_DURATION ?? 60),
    sessionPrice: Number(process.env.PORTAL_SESSION_PRICE ?? 150),
  };
}

/** First session: ≥7 days after assessment, on configured weekday/time (US Eastern). */
export function getFirstWeeklySlot(
  after: Date,
  config: SessionScheduleConfig,
): Date {
  let candidate = addEasternDays(after, 7);
  let parts = getEasternParts(candidate);
  candidate = easternToUtc(
    parts.year,
    parts.month,
    parts.day,
    config.hour,
    config.minute,
  );

  for (let i = 0; i < 7; i++) {
    if (getEasternParts(candidate).weekday === config.weekday) break;
    candidate = addEasternDays(candidate, 1);
    parts = getEasternParts(candidate);
    candidate = easternToUtc(
      parts.year,
      parts.month,
      parts.day,
      config.hour,
      config.minute,
    );
  }

  const minTime = after.getTime() + 7 * 24 * 60 * 60 * 1000;
  while (candidate.getTime() < minTime) {
    candidate = addEasternDays(candidate, 7);
    parts = getEasternParts(candidate);
    candidate = easternToUtc(
      parts.year,
      parts.month,
      parts.day,
      config.hour,
      config.minute,
    );
  }

  return candidate;
}

export function addWeeks(date: Date, weeks: number): Date {
  return addEasternDays(date, weeks * 7);
}

export async function createPackageSessionsForAssessment(
  patientId: string,
  assessmentId: string,
  packageNumber: number,
  sessionCount: number,
  completedAt: Date,
  durationMins?: number,
) {
  const existing = await prisma.session.count({
    where: { assessmentId, status: { not: "cancelled" } },
  });
  if (existing > 0) {
    return { created: 0, skipped: true };
  }

  const config = getSessionScheduleConfig();
  const sessionDuration = durationMins ?? config.durationMins;
  let slot = getFirstWeeklySlot(completedAt, config);
  const sessions = [];

  for (let i = 1; i <= sessionCount; i++) {
    sessions.push({
      patientId,
      assessmentId,
      sessionIndex: i,
      scheduledAt: new Date(slot),
      durationMins: sessionDuration,
      notes: `Package ${packageNumber} — Session ${i} of ${sessionCount}`,
      status: "scheduled",
    });
    slot = addWeeks(slot, 1);
  }

  await prisma.session.createMany({ data: sessions });
  return { created: sessionCount, skipped: false };
}

export async function resetSessionAutomationOnReschedule(sessionId: string) {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    include: { invoice: true },
  });
  if (!session) return;

  if (
    session.invoice?.autoGenerated &&
    session.invoice.status === "pending"
  ) {
    await prisma.invoice.delete({ where: { id: session.invoice.id } });
  }

  await prisma.session.update({
    where: { id: sessionId },
    data: {
      patientReminderSentAt: null,
      doctorReminderSentAt: null,
    },
  });
}
